# Internal role variables specific to: SUSE (os_family)
#
# Only values specific to the platform and its functionality should be included
# here. Variables in this file override those defined in vars/main.yml.

---

__run_fail2ban_packages_install_map_backends:
  pyinotify:
    - "python3-pyinotify" # Python bindings for the inotify mechanism wrapper
  systemd:
    - "python3-systemd" # Python bindings for native access to the systemd facilities
