# Services and daemons: Manage their state, configure, or create them.

---

- name: "Service | Default | Ensure service state: {{ __run_fail2ban_fail2ban_servicename }}"
  ansible.builtin.service:
    name: "{{ __run_fail2ban_fail2ban_servicename }}"
    state: "{{ 'started' if run_fail2ban_service_state in ['enabled', 'running'] else 'stopped' if run_fail2ban_service_state == 'disabled' }}"
    enabled: "{{ true if run_fail2ban_service_state == 'enabled' else false if run_fail2ban_service_state in ['disabled', 'running'] }}"
  when:
    - run_fail2ban_service_state != 'unmanaged'
