# Handlers: Tasks that are triggered and run only when notified.

---

- name: "Handlers | fail2ban.service restart"
  ansible.builtin.systemd_service:
    name: "{{ __run_fail2ban_fail2ban_servicename }}"
    state: "restarted"
  listen: "run_fail2ban: restart fail2ban.service"
  when:
    - run_fail2ban_service_state != 'unmanaged'
