# Initialization: Manage internal role setup and the Ansible environment.

---

- name: "Init | Gather role-specific facts"
  ansible.builtin.setup:
    gather_subset: "{{ __run_fail2ban_used_facts }}"
  when:
    - not (__run_fail2ban_used_facts is subset(ansible_facts.keys()))


- name: "Init | Include role meta data"
  ansible.builtin.include_vars:
    file: "../meta/main.yml"
    name: "__run_fail2ban_meta"


- name: "Init | Check Ansible version requirement and fail if unmet"
  ansible.builtin.fail:
    msg: >
      This role requires Ansible {{ __run_fail2ban_meta['galaxy_info']['min_ansible_version'] }}
      or higher. You are currently running Ansible {{ ansible_version['full'] }} .
  when:
    - ansible_version['full'] is version_compare(__run_fail2ban_meta['galaxy_info']['min_ansible_version'], '<')


- name: "Init | Notify when platform support check is not possible"
  ansible.builtin.debug:
    msg: >
      The list of supported platforms cannot be checked as it is either empty
      or distribution facts are missing.
    verbosity: 1
  when:
    - ansible_facts['os_family'] is not ansible.builtin.defined or
      ansible_facts['distribution'] is not ansible.builtin.defined or
      ansible_facts['distribution_version'] is not ansible.builtin.defined or
      ansible_facts['distribution_major_version'] is not ansible.builtin.defined or
      ((__run_fail2ban_supported_platforms | ansible.builtin.length) == 0)


- name: "Init | Warn when platform is unsupported"
  ansible.builtin.fail:
    msg: >
      Neither {{ ansible_facts['distribution'] }} (distribution) nor {{ ansible_facts['os_family'] }} (os_family)
      with versions '{{ ansible_facts['distribution_major_version'] }}', '{{ ansible_facts['distribution_version'] }}',
      or 'all' is in the list of supported platforms from vars/main.yml: {{ __run_fail2ban_supported_platforms }}
  vars:
    __run_fail2ban_platform_names_regex: >-
      ^({{ ansible_facts['distribution'] }}|{{ ansible_facts['os_family'] }})$
    __run_fail2ban_platform_versions_regex: >-
      ^({{ ansible_facts['distribution_major_version'] }}|{{ ansible_facts['distribution_version'] }}|all)$
    __run_fail2ban_matched_versions: >-
      {{
        __run_fail2ban_supported_platforms
        | ansible.builtin.selectattr('name', 'match', __run_fail2ban_platform_names_regex, ignorecase=true)
        | ansible.builtin.map(attribute='versions')
        | ansible.builtin.flatten
        | ansible.builtin.select('match', __run_fail2ban_platform_versions_regex, ignorecase=true)
        | ansible.builtin.list
      }}
  when:
    - (__run_fail2ban_supported_platforms | ansible.builtin.length) > 0
    - (__run_fail2ban_matched_versions | ansible.builtin.length) == 0
  ignore_errors: true # noqa: ignore-errors


- name: "Init | Set platform-specific filename list (most to least specific; raw with possible duplicates)"
  ansible.builtin.set_fact:
    __run_fail2ban_platform_filenames_raw:
      - "{{ __run_fail2ban_dist }}_{{ __run_fail2ban_dist_ver }}.yml"
      - "{{ __run_fail2ban_dist }}_{{ __run_fail2ban_dist_major }}.yml"
      - "{{ __run_fail2ban_dist }}.yml"
      - "{{ __run_fail2ban_os_family }}.yml"
  vars:
    __run_fail2ban_dist: >-
      {{
        ansible_facts['distribution']
        | ansible.builtin.regex_replace(' ', '_')
        | ansible.builtin.lower
      }}
    __run_fail2ban_dist_ver: >-
      {{
        ansible_facts['distribution_version']
        | ansible.builtin.regex_replace(' ', '_')
        | ansible.builtin.lower
      }}
    __run_fail2ban_dist_major: >-
      {{
        ansible_facts['distribution_major_version']
        | ansible.builtin.regex_replace(' ', '_')
        | ansible.builtin.lower
      }}
    __run_fail2ban_os_family: >-
      {{
        ansible_facts['os_family']
        | ansible.builtin.regex_replace(' ', '_')
        | ansible.builtin.lower
      }}


- name: "Init | Set unique platform-specific filename list (most to least specific)"
  ansible.builtin.set_fact:
    __run_fail2ban_platform_filenames_most_specific_first: >-
      {{
        (__run_fail2ban_platform_filenames_raw
        | ansible.builtin.unique
        | ansible.builtin.default([]))
      }}


- name: "Init | Set unique platform-specific filename list (least to most specific)"
  ansible.builtin.set_fact:
    __run_fail2ban_platform_filenames_most_specific_last: >-
      {{
        __run_fail2ban_platform_filenames_most_specific_first
        | ansible.builtin.reverse
      }}


- name: "Init | Include platform-specific variables (if any), overwrite values with more specific ones"
  ansible.builtin.include_vars:
    file: "{{ __run_fail2ban_vars_file }}"
  vars:
    __run_fail2ban_vars_file: "{{ role_path }}/vars/{{ item }}"
  when:
    - __run_fail2ban_vars_file is ansible.builtin.file
  loop: "{{ __run_fail2ban_platform_filenames_most_specific_last }}"
